spring:
  application:
   name: outdoor
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/outdoor_help?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: xxx #填入账号
    password: xxx #填入密码
server:
  port: 8080
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
agent:
  dify:
    enabled: true
    api-url: #填入url
    file-upload-url: #填入url
    api-key: #填入key
    user-prefix: xingzhi-user-
